import { Vehicle, ActivityItem } from "@/types";

export const vehicles: Vehicle[] = [
  {
    id: "1",
    name: "2021 Tesla Model 3",
    price: 35500,
    mileage: 24100,
    condition: "Excellent",
    location: "Seattle, WA",
    image: "/images/tesla1.png",
    images: ["/images/tesla1.png", "/images/tesla1.png", "/images/tesla1.png", "/images/tesla1.png"],
    description: "This stunning 2021 Tesla Model 3 Long Range is in excellent condition with only 24,100 miles. Features include Autopilot, Premium Interior, and Full Self-Driving Capability. Single owner, clean title, and full service history available.",
    features: ["Autopilot", "Premium Interior", "Full Self-Driving Capability", "Heated Seats", "Glass Roof", "Premium Audio", "Navigation", "Mobile Connector"],
    specs: {
      year: "2021",
      make: "Tesla",
      model: "Model 3",
      trim: "Long Range",
      fuelType: "Electric",
      transmission: "Automatic",
      drivetrain: "AWD",
      exteriorColor: "Pearl White",
    },
    estimatedValue: 38000,
    currentHighBid: 33000,
  },
  {
    id: "2",
    name: "2019 Porsche 718",
    price: 58000,
    mileage: 12500,
    condition: "Pristine",
    location: "Los Angeles, CA",
    image: "/images/Porsche.png",
    images: ["/images/Porsche.png", "/images/Porsche.png", "/images/Porsche.png", "/images/Porsche.png"],
    description: "Stunning 2019 Porsche 718 in pristine condition with only 12,500 miles. This sports car delivers an exhilarating driving experience with a turbocharged flat-four engine.",
    features: ["Sport Chrono Package", "Bose Audio", "Heated Seats", "Navigation", "Parking Sensors", "Lane Keep Assist", "Blind Spot Monitor", "Apple CarPlay"],
    specs: {
      year: "2019",
      make: "Porsche",
      model: "718",
      trim: "Cayman S",
      fuelType: "Gasoline",
      transmission: "PDK",
      drivetrain: "RWD",
      exteriorColor: "Guards Red",
    },
    estimatedValue: 62000,
    currentHighBid: 55000,
  },
  {
    id: "3",
    name: "2023 Toyota Tundra",
    price: 52400,
    mileage: 5200,
    condition: "New",
    location: "Denver, CO",
    image: "/images/Toyota.png",
    images: ["/images/Toyota.png", "/images/Toyota.png", "/images/Toyota.png", "/images/Toyota.png"],
    description: "Nearly new 2023 Toyota Tundra with only 5,200 miles. This full-size truck combines power and luxury with a twin-turbocharged V6 engine and premium features throughout.",
    features: ["Toyota Safety Sense", "JBL Audio", "Heated & Ventilated Seats", "Wireless CarPlay", "Multi-Terrain Monitor", "Panoramic Moonroof", "Power Running Boards", "Tow Package"],
    specs: {
      year: "2023",
      make: "Toyota",
      model: "Tundra",
      trim: "Platinum",
      fuelType: "Hybrid",
      transmission: "Automatic",
      drivetrain: "4WD",
      exteriorColor: "Wind Chill Pearl",
    },
    estimatedValue: 58000,
    currentHighBid: 50000,
  },
];

export const allVehicles: Vehicle[] = [
  {
    id: "v1",
    name: "2020 Honda Accord",
    price: 24900,
    mileage: 32450,
    condition: "Excellent",
    location: "Austin, TX",
    image: "/images/1.png",
    images: ["/images/1.png", "/images/1.png", "/images/1.png", "/images/1.png"],
    estimatedValue: 27000,
    currentHighBid: 21000,
    description: "Well-maintained 2020 Honda Accord with low mileage. Single owner, clean title, full service history available.",
    features: ["Apple CarPlay", "Android Auto", "Heated Seats", "Lane Assist", "Backup Camera", "Sunroof"],
    specs: {
      year: "2020",
      make: "Honda",
      model: "Accord",
      trim: "Sport",
      fuelType: "Gasoline",
      transmission: "Automatic",
      drivetrain: "FWD",
      exteriorColor: "Lunar Silver",
    },
  },
  {
    id: "v2",
    name: "2022 Ford Explorer",
    price: 41200,
    mileage: 18900,
    condition: "Excellent",
    location: "Miami, FL",
    image: "/images/2.png",
    images: ["/images/2.png", "/images/2.png", "/images/2.png", "/images/2.png"],
    estimatedValue: 44000,
    currentHighBid: 38000,
    description: "2022 Ford Explorer in excellent condition. Perfect family SUV with third-row seating and advanced safety features.",
    features: ["Third Row Seating", "SYNC 4", "Heated Seats", "360 Camera", "Blind Spot Monitor", "Tow Package"],
    specs: {
      year: "2022",
      make: "Ford",
      model: "Explorer",
      trim: "XLT",
      fuelType: "Gasoline",
      transmission: "Automatic",
      drivetrain: "AWD",
      exteriorColor: "Carbonized Gray",
    },
  },
  {
    id: "v3",
    name: "2021 Tesla Model 3",
    price: 35500,
    mileage: 24100,
    condition: "Excellent",
    location: "Seattle, WA",
    image: "/images/tesla1.png",
    images: ["/images/tesla1.png", "/images/tesla1.png", "/images/tesla1.png", "/images/tesla1.png"],
    estimatedValue: 38000,
    currentHighBid: 33000,
    description: "2021 Tesla Model 3 Long Range in excellent condition. Full Self-Driving capability included.",
    features: ["Autopilot", "Premium Interior", "Full Self-Driving", "Heated Seats", "Glass Roof", "Premium Audio"],
    specs: {
      year: "2021",
      make: "Tesla",
      model: "Model 3",
      trim: "Long Range",
      fuelType: "Electric",
      transmission: "Automatic",
      drivetrain: "AWD",
      exteriorColor: "Pearl White",
    },
  },
  {
    id: "v4",
    name: "2019 Porsche 718",
    price: 58000,
    mileage: 12500,
    condition: "Pristine",
    location: "Los Angeles, CA",
    image: "/images/Porsche.png",
    images: ["/images/Porsche.png", "/images/Porsche.png", "/images/Porsche.png", "/images/Porsche.png"],
    estimatedValue: 62000,
    currentHighBid: 55000,
    description: "Stunning 2019 Porsche 718 in pristine condition. Exhilarating driving experience with turbocharged engine.",
    features: ["Sport Chrono", "Bose Audio", "Heated Seats", "Navigation", "Parking Sensors", "Apple CarPlay"],
    specs: {
      year: "2019",
      make: "Porsche",
      model: "718",
      trim: "Cayman S",
      fuelType: "Gasoline",
      transmission: "PDK",
      drivetrain: "RWD",
      exteriorColor: "Guards Red",
    },
  },
  {
    id: "v5",
    name: "2021 BMW 5 Series",
    price: 44900,
    mileage: 21000,
    condition: "Excellent",
    location: "Chicago, IL",
    image: "/images/5.png",
    images: ["/images/5.png", "/images/5.png", "/images/5.png", "/images/5.png"],
    estimatedValue: 48000,
    currentHighBid: 42000,
    description: "2021 BMW 5 Series with premium package. Luxury sedan combining performance and comfort.",
    features: ["Harman Kardon Audio", "Heated Seats", "Gesture Control", "Parking Assistant", "Head-Up Display", "Wireless Charging"],
    specs: {
      year: "2021",
      make: "BMW",
      model: "5 Series",
      trim: "530i",
      fuelType: "Gasoline",
      transmission: "Automatic",
      drivetrain: "RWD",
      exteriorColor: "Alpine White",
    },
  },
  {
    id: "v6",
    name: "2023 Toyota Tundra",
    price: 52400,
    mileage: 5200,
    condition: "New",
    location: "Denver, CO",
    image: "/images/Toyota.png",
    images: ["/images/Toyota.png", "/images/Toyota.png", "/images/5.png", "/images/Toyota.png"],
    estimatedValue: 58000,
    currentHighBid: 50000,
    description: "Nearly new 2023 Toyota Tundra Platinum with twin-turbo V6 hybrid engine and premium features.",
    features: ["Toyota Safety Sense", "JBL Audio", "Heated Seats", "Wireless CarPlay", "Moonroof", "Tow Package"],
    specs: {
      year: "2023",
      make: "Toyota",
      model: "Tundra",
      trim: "Platinum",
      fuelType: "Hybrid",
      transmission: "Automatic",
      drivetrain: "4WD",
      exteriorColor: "Wind Chill Pearl",
    },
  },
];

export const activities: ActivityItem[] = [
  {
    id: "1",
    text: "Shaun registered for Elite Soccer Training",
    time: "2 hours ago",
    status: "green",
  },
  {
    id: "2",
    text: "Price drop alert: 2021 Audi A4",
    time: "Yesterday",
    status: "yellow",
  },
  {
    id: "3",
    text: "Purchase completed: 2020 Honda Accord",
    time: "3 days ago",
    status: "blue",
  },
];

export const messages = [
  {
    id: "1",
    sender: "Admin Support",
    preview: "Your bid on the Honda Accord has been confirmed.",
    avatar: "/icons/aad.png",
  },
  {
    id: "2",
    sender: "Billing",
    preview: "Invoice #12345 has been generated.",
    avatar: "/icons/ccaa.png",
  },
];

export const stats = [
  {
    id: "1",
    title: "New Vehicles",
    value: 24,
    icon2: "/icons/trend.svg",
    badge: "+12%",
    badgeColor: "text-green-500",
    icon: "/icons/car.svg",
  },
  {
    id: "2",
    title: "Active Bids",
    value: 7,
    icon2: "/icons/live.svg",
    badge: "Live",
    badgeColor: "text-[#00D492]",
    icon: "/icons/hammer.svg",
  },
  {
    id: "3",
    title: "Saved Vehicles",
    value: 12,
    icon2: "/icons/plus.svg",
    badge: "2 New",
    badgeColor: "text-[#00D492]",
    icon: "/icons/bookmark.svg",
  },
  {
    id: "4",
    title: "Purchased",
    value: 3,
    icon2: "/icons/Closed.svg",
    badge: "Closed",
    badgeColor: "text-[#00D492]",
    icon: "/icons/pur.svg",
  },
];